name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:                                  # ← bu blok birden fazla job tutar

  test:                                # ← 1. JOB (2 boşluk girinti)
    runs-on: ubuntu-latest
    steps:
      - name: Kodu çek
        uses: actions/checkout@v4
      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Bağımlılıkları kur
        run: pip install -r requirements.txt
      - name: Testleri çalıştır
        run: pytest -v

  lint:                                # ← 2. JOB (test ile AYNI hizada, 2 boşluk)
    runs-on: ubuntu-latest
    steps:
      - name: Kodu çek
        uses: actions/checkout@v4
      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Ruff kur
        run: pip install ruff
      - name: Kod kalitesini denetle
        run: ruff check .
